$("#britishpin").click(function(){
  $("#britishfood").toggleClass("hidden");
});
$(#"chinapin").click(function(){
  $("#chinesefood").toggleClass("hidden");
});
$(#"morrocopin").click(function(){
  $("#morrocanfood").toggleClass("hidden");
});
$(#"turkeypin").click(function(){
  $("#turkishfood").toggleClass("hidden");
});
$(#"pakistanpin").click(function(){
  $("#pakistanifood").toggleClass("hidden");
});
$(#"palestinepin").click(function(){
  $("#palestinianfood").toggleClass("hidden");
});
$(#"thaipin").click(function(){
  $("#thaifood").toggleClass("hidden");
});
$(#"japanpin").click(function(){
  $("#japnesefood").toggleClass("hidden");
});
